"""THIS SECTION WAS GENERATED BY zenith/shim. DO NOT MODIFY."""

# ---metadata
# name: Launch File
# ---
"""END OF GENERATED SECTION"""


from launch import LaunchDescription
from launch.actions import RegisterEventHandler, LogInfo
from launch.event_handlers import OnProcessStart
from launch_ros.actions import Node

from launch_node_definitions import map_manager_carla

"""THIS SECTION WAS GENERATED BY zenith/shim. DO NOT MODIFY."""
# ---launch_list
LAUNCH_LIST = [
    Node(package="rviz", executable="rviz"),
    Node(package="joy_translation1", executable="joy_translation_node"),
    Node(package="clock", executable="clock_node"),
    Node(package="helpers", executable="routing_listener"),
    Node(package="helpers", executable="routing_monitor"),
    Node(package="airbags", executable="airbag_node"),
    Node(package="guardian", executable="guardian_node"),
    Node(package="guardian", executable="sound_node"),
]
# ---
"""END OF GENERATED SECTION"""


def generate_launch_description():
    return LaunchDescription(
        [
            map_manager_carla,
            RegisterEventHandler(
                OnProcessStart(
                    target_action=map_manager_carla,
                    on_start=[
                        LogInfo(
                            msg="Map Manager Started... launching the rest of Navigator..."
                        ),
                        """THIS SECTION WAS GENERATED BY zenith/shim. DO NOT MODIFY."""
                        # ---launch__list_insert
                        * LAUNCH_LIST,
                        # ---
                        """END OF GENERATED SECTION""",
                    ],
                )
            ),
        ]
    )
