services:
  sim:
    build:
      context: .
      dockerfile: Dockerfile
      platforms: ["linux/arm64"]
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_DOMAIN_ID=23
      - ROS_LOCALHOST_ONLY=0
    command: >
      bash -lc "ros2 launch turtlesim_tasks sim_bringup.launch.py"

  follower:
    build:
      context: .
      dockerfile: Dockerfile
      platforms: ["linux/arm64"]
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_DOMAIN_ID=23
      - ROS_LOCALHOST_ONLY=0
    command: >
      bash -lc "ros2 launch turtlesim_tasks follower_bringup.launch.py"
