#!/bin/sh
apt-get update
apt-get install -y ros-eloquent-ros-testing
apt-get install -y python3-psutil
apt-get install -y ros-eloquent-qt-dotgraph
apt-get install -y ros-eloquent-osrf-testing-tools-cpp
apt-get install -y ros-eloquent-lanelet2-core
apt-get install -y ros-eloquent-lanelet2-io
apt-get install -y ros-eloquent-lanelet2-projection
apt-get install -y ros-eloquent-lanelet2
apt-get install -y libgeographic-dev
apt-get install -y ros-eloquent-apex-test-tools
apt-get install -y ros-eloquent-raptor-dbw-msgs
apt-get install -y ros-eloquent-ros2-socketcan
apt-get install -y ros-eloquent-lgsvl-msgs
apt-get install -y libcgal-dev
apt-get install -y ros-eloquent-point-cloud-msg-wrapper
apt-get install -y ros-eloquent-acado-vendor
apt-get install -y ros-eloquent-ament-cmake-google-benchmark
apt-get install -y ros-eloquent-rviz2
apt-get install -y ros-eloquent-osqp-vendor
apt-get install -y python3-tornado
apt-get install -y python3-twisted
apt-get install -y ros-eloquent-rosauth
apt-get install -y libomp-dev
apt-get install -y libpcl-dev
apt-get install -y ros-eloquent-lanelet2-traffic-rules
apt-get install -y ros-eloquent-lanelet2-routing
apt-get install -y python3-matplotlib
apt-get install -y python3-scipy
apt-get install -y libboost-system-dev
apt-get install -y ros-eloquent-automotive-platform-msgs
apt-get install -y ros-eloquent-casadi-vendor
apt-get install -y libopenblas-dev
apt-get install -y libopencv-dev
apt-get install -y ros-eloquent-tvm-vendor
apt-get install -y ros-eloquent-pcl-conversions
apt-get install -y libyaml-cpp-dev
apt-get install -y ros-eloquent-vision-opencv
apt-get install -y ros-eloquent-cv-bridge
apt-get install -y python3-pil
apt-get install -y python3-bson
apt-get install -y ros-eloquent-udp-driver
apt-get install -y ros-eloquent-joy
apt-get install -y ros-eloquent-joy-linux
apt-get install -y ros-eloquent-rviz-common
apt-get install -y ros-eloquent-rviz-default-plugins
apt-get install -y qtbase5-dev
apt-get install -y libqt5widgets5
apt-get install -y ros-eloquent-lgsvl-bridge
apt-get install -y ros-eloquent-velodyne
apt-get install -y ros-eloquent-angles
apt-get install -y libpcap-dev
