# Package:   nova_msgs
# Filename:  SafetyCommand.srv
# Author:    Joshua Williams
# Email:     joshmackwilliams@protonmail.com
# Copyright: 2021, Nova UTD
# License:   MIT License

# The service the safety manager uses to assign recovery strategies to nodes
# See https://github.com/Nova-UTD/navigator/wiki/Safety-Manager-Design

# Which of the node's strategies to use
# 0 is reserved for normal operation
# 255 is reserved for termination
uint8 strategy

# Sequence number, to ensure messages can't be processed out of order
uint32 sequence_number

# JSON-formatted command-specific data
string additional_data

---

# We send nothing back, but this is used as an acknowledgement