/**:
  ros__parameters:
    ip: "0.0.0.0"
    port: 2368
    cloud_size:  55000
    topic: "points_raw"  # UdpDriverNode strictly expects to get the topic via `declare_parameter`.
    frame_id: "lidar_left"
    timeout_ms: 10
    rpm:        600
