/**:
    ros__parameters:

      # KF parameters
      state_func_covariance: 100
      measure_func_covariance: 0.001
      prediction_score_decay: 0.03
      lidar_scanning_frequency: 10

      # max prediction number of state function
      max_prediction_num: 16
      max_prediction_num_for_new_object: 2

      # detection score threshold
      input_score_threshold: 0.7
      init_score_threshold: 0.7
      update_score_threshold: 0.0
      post_score_threshold: 0.0

      # tracking latency (s)
      # -1: global tracking
      # 0.->500: online or near online tracking
      latency: 0