# config/test.param.yaml
---
lidar_rear:
  point_cloud_filter_transform_node:
    ros__parameters:
      timeout_ms:       110
      pcl_size:         55000
      input_frame_id:  "lidar_rear"
      output_frame_id: "base_link" # Use URDF transform
      init_timeout_ms:  5000
      expected_num_subscribers: 1
      expected_num_publishers:  1
      start_angle:            3.7      # radius
      end_angle:              2.0
      min_radius:             1.5           # meters
      max_radius:             150.0
      static_transformer:
        quaternion:
          x:                    0.032584 #0.0
          y:                    0.0081743 #0.0
          z:                    0.9693964 #0.9699438633
          w:                    0.2431915 #0.2433287941
        translation:
          x:                    0.52
          y:                   -0.72
          z:                    1.0
