# config/test.param.yaml
---
lidar_right:
  point_cloud_filter_transform_node:
    ros__parameters:
      timeout_ms:       110
      pcl_size:         55000
      input_frame_id:  "lidar_right"
      output_frame_id: "base_link"
      init_timeout_ms:  5000
      expected_num_subscribers: 1
      expected_num_publishers:  1
      start_angle:            4.61      # radius
      end_angle:              2.85
      min_radius:             1.5           # meters
      max_radius:             150.0
      static_transformer:
        quaternion:
          x:                    0.0
          y:                    0.0
          z:                   -0.6631354427
          w:                    0.7484994220
        translation:
          x:                    1.43
          y:                    3.35
          z:                    0.7876
