FROM ros:foxy

ENV DEBIAN_FRONTEND noninteractive

RUN git clone --recurse-submodules -b leaderboard-2.0 --single-branch https://github.com/carla-simulator/ros-bridge

WORKDIR /ros-bridge
RUN rosdep install --from-paths . --ignore-src

RUN apt update && apt install ros-foxy-pcl-conversions \
    ros-foxy-rviz-common