# MSG for one image sent to lane detection model
string currentlane      # Type of lane that the vehicle currently is in (e.g. straight lane, right turn lane, left turn lane)
string[] alllanes       # All of the different lanes on the road, ordered from left to right
int32 totallanecount       # Total number of lanes on the road
int32 numlanesleftofcurrent    #Number of lanes left of the current lane of travel
