# MSG for one specific pedestrian intending on entering the road
float32 x               # X-coordinate of the pedestrian bounding box
float32 y               # Y-coordinate of the pedestrian bounding box
float32 width           # Width of the pedestrian bounding box
float32 height          # Height of the pedestrian bounding box
float32 distance        # Horizontal distance between the pedestrian and the road