# MSG for one road user detection
float32 x               # The horizontal coordinate of the detected road user
float32 y               # The vertical coordinate of the detected road user
float32 width           # The width of the detected road user
float32 height          # The height of the detected road user
float32 confidence      # The confidence of the detection
string detection        # The type of user detected (Bicycle, Bus, Car, Motorcycle, Pedestrian, Train, Truck)