# MSG for one specific Traffic light
float32 x           # X-coordinate of the traffic light bounding box
float32 y           # Y-coordinate of the traffic light bounding box
float32 width       # Width of the traffic light bounding box
float32 height      # Height of the traffic light bounding box
uint8 label         # Label indicating the class of the traffic light (e.g., 0 for stop, 1 for warning, 2 for go)
float32 score       # Confidence score of the traffic light detection
