version: '2.3'
name: carla_bridge
services:
    carla_bridge:
        privileged: true
        stdin_open: true
        tty: true
        runtime: nvidia

        image: carla_bridge
        container_name: carla_bridge_${USER}

        volumes:     
          - type: bind
            source: /home/share/carla
            target: /carla
          - type: bind
            source: ${HOME}/.Xauthority
            target: /root/.Xauthority
          - type: bind
            source: /tmp/.X11-unix
            target: /tmp/.X11-unix

        environment:
          - DISPLAY=:1
          - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
          - NVIDIA_VISIBLE_DEVICES=all

        build:
          context: .
          dockerfile: Dockerfile
        
        network_mode: "host"