# param/robot_localization.param.yaml
---
/**:
  ros__parameters:
    frequency: 10.0 # Estimate update frequency, Hz, double
    world_frame: "map"
    two_d_mode: true

    odom0: "/odometry/gnss_raw" # xyz and yaw
    odom0_config:
      [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ]

    imu0: "/carla/hero/imu" # Angular vel, linear acc
    imu0_config:
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
      ]

    # twist0: "/twist0" # Only use x velocity (speedometer)
    # twist0_config: [false, false, false, false, false, false,
    #                true, false, false, true, true, false,
    #                false, false, false]
