# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Navigator
description: >- # this means to ignore newlines until "baseurl:"
  Navigator is an open-source autonomous driving system developed
  by Nova, an applied research group at UT Dallas.
baseurl: "/navigator" # the subpath of your site, e.g. /blog
url: "https://nova-utd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: "nova-utd.github.io"
github_username:  nova-utd
logo: "/assets/res/logo.png"

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
color_scheme: novalicious

# Aux links for the upper right navigation
aux_links:
  "Learn about Nova":
    - "//nova-utd.github.io"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# External navigation links
nav_external_links:
  - title: Learn about Nova
    url: https://nova-utd.github.io
    hide_icon: false # set to true to hide the external link icon - defaults to false

callouts:
  warning:
    title: Warning
    color: red
  example:
    title: Example
    color: green

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
