# Skeleton joints indices for BODY_FORMAT::POSE_18
#        16-14   15-17
#             \ /
#              0
#              |
#       2------1------5
#       |    |   |    |
#	    |    |   |    |
#       3    |   |    6
#       |    |   |    |
#       |    |   |    |
#       4    8   11   7
#            |   |
#            |   |
#            |   |
#            9   12
#            |   |
#            |   |
#            |   |
#           10   13

# Skeleton joints indices for BODY_FORMAT::POSE_34
#                     30  28
#                       \/
#                   31  27  29
#                    \  |  /
#                       26
#                       |
# 16-15-14---13--12-11  03  04-05--06---07-08-09
#       /             \ | /              \        #
#      17               02                10
#                       |
#                       01
#                       |
#                       |
#                    22-00-18
#                     |    |
#                     |    |
#                     |    |
#                    23    19
#                     |    |
#                     |    |
#                     |    |
#                    24    20
#                     |    |
#                    25    21

zed_interfaces/Keypoint2Df[34] keypoints
