pcl_localization:
  ros__parameters:
    registration_method: "NDT"
    ndt_resolution: 2.0
    ndt_step_size: 0.4
    transform_epsilon: 0.01
    voxel_leaf_size: 1.0
    scan_max_range: 100.0
    scan_min_range: 1.0
    scan_period: 0.1
    use_pcd_map: false
    map_path: "/home/main/navigator-2/data/maps/grand_loop/grand_loop.pcd"
    set_initial_pose: true
    initial_pose_x: -173.19412151241747
    initial_pose_y: 30.456777493247237
    initial_pose_z: -0.002422069227261403
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.7238698054713825
    initial_pose_qw: -0.6899365947149223
    use_odom: false
    use_imu: false
    enable_debug: true
    fitness_gnss_threshold: 55.0
    dist_gnss_threshold: 5.0
